ouster-lidar/ouster-ros

CHANGELOG.rst
CMakeLists.txt
Dockerfile
launch/record.launch
launch/sensor.launch

* Closes #3 
* Update `LICENSE` file installation instructions
* Removed the installation of `LICENSE-bin` as deemed unnecessary.
* Update `Dockerfile` to check for installation errors
* Add 4096x5 lidar mode to launch files
Use catkin_make command to build and install the project 
```bash
catkin_make
catkin_make install
```

FSW-4177: update cmake install lines for ouster ros

---

include/ouster_ros/os_client_base_nodelet.h
launch/common.launch
launch/record.launch
launch/replay.launch
launch/sensor.launch
src/os_cloud_nodelet.cpp
src/os_replay_nodelet.cpp
src/os_sensor_nodelet.cpp

- N/A
- Adjust argument parsing such that it is known which args are required and which are optional
- Allow the user to pass `timestamp_mode` during replay to override the timestamp on IMU and LIDAR packets. 
* The following command should reflect the exact requirement of what is considered a required roslaunch file argument as specified in the [usage section](https://github.com/ouster-lidar/ouster-ros#usage) of the repo readme file
```bash
roslaunch ouster_ros sensor.launch --ros-args
roslaunch ouster_ros record.launch --ros-args
roslaunch ouster_ros replay.launch --ros-args
```
* Invoking `roslaunch ouster_ros sensor.launch` without specifying `sensor_hostname` should fail immediately
* Invoking `record.launch` or `replay.launch` without specifying `metadata` should fail immediately.
* …

SW-4007: State default argument in the ros launch files for optional ones

---

CHANGELOG.rst
launch/record.launch
launch/sensor.launch
src/os_sensor_nodelet.cpp

Closes #20  
- Feed `udp_dest` value set by the user from either `sensor.launch` or `record.launch`
- Fix minor typos
* Rest the sensor udp dest to local
* Execute the following launch sequence
```bash
roslaunch ouster_ros sensor.launch sensor_hostname:=$SENSOR_HOSTNAME udp_dest:=$UDP_DEST
```
* Observe that the sensor now uses the selected `$UDP_DEST` value specified during launch

SW-4278: ros driver doesn't use correct udp_dest given by user during launch

---

CHANGELOG.rst
CMakeLists.txt
docs/migration-guide.rst
include/ouster_ros/os_client_base_nodelet.h
include/ouster_ros/os_point.h
include/ouster_ros/os_ros.h
package.xml
src/os_client_base_nodelet.cpp
src/os_cloud_nodelet.cpp
src/os_image_nodelet.cpp
src/os_replay_nodelet.cpp
src/os_ros.cpp
src/os_sensor_nodelet.cpp

- Closes #9 
- Update published TF transforms time with senosr or ros time based on the active timestamp mode
- Renamed `ros.h` and `point.h` to `os_ros.h` and `point.h`
- Updated code files copyrights period
- Updated driver version to `0.6.0`
A. With _timestamp_mode_ set **TIME_FROM_ROS_TIME**
1. Launch the driver either through live or replay mode with _timestamp_mode_ set to **TIME_FROM_ROS_TIME**
```bash
SENSOR_HOSTNAME=<sensor>
roslaunch ouster_ros sensor.launch \
sensor_hostname:=$SENSOR_HOSTNAME \
timestamp_mode:=TIME_FROM_ROS_TIME
```
2. In a separate terminal, observe the timestamp of both **os_imu** and **os_lidar** frame with respect to **os_sensor**
```bash
rosrun tf tf_echo os_sensor os_imu
rosrun tf tf_echo os_sensor os_lidar
```
3. The timestamp of both transform messages …

SW-4250: Update published TF transforms time with senosr or ros time based on the active timestamp mode

---

CHANGELOG.rst
Dockerfile
README.md
package.xml

https://github.com/ouster-lidar/ouster_example/pull/456
- Propagating ouster-sdk release to ouster-ros
- ouster-sdk changes:
- Additions:
- Add init_logger() method to control logs emitted by ouster_client
- Parsing for FW 3.0/2.5 thermal features
- convenience string output functions for LidarScan
- new flag CONFIG_FORCE_REINIT for set_config() method to force reinit
- improvements to the ouster_viz library
- Breaking changes:
- signal multiplier type changed to double
- make_xyz_lut takes mat4d instead of double to handle tf from beam to lidar frame
- drop default parameters from shortform init_client()
- drop default parameters of Python client.Sensor() constructor
- change Python Scans interface timeout to default to 1 second instead of None
- Bug Fixes:
- Address processed frame drop …

SW-4328: Update ouster-sdk to 2.5/3.0 FW release

---

CHANGELOG.rst
package.xml
src/os_sensor_nodelet.cpp

- N/A
- Revise **ouster-ros** `set_config`/`init_client` sequence after release to avoid double set_config invocations
- Validate port numbers before `set_config`
- Inform user when a random port number is going to be assigned
- Refactor code
A. Invalid ports case
1. Negative port value
```bash
roslaunch ouster_ros sensor.launch \
sensor_hostname:=$SENSOR_HOSTNAME \
lidar_port:=-1000  # ports can't be assigned a negative value.
```
The client should exit immediately. repeat again with the `imu_port`
2. Positive but out of range port value
```bash
roslaunch ouster_ros sensor.launch \
sensor_hostname:=$SENSOR_HOSTNAME \
lidar_port:=1000000  # ports can't be assigned a value greater than 65535
```
B. Zero values 
1. Assign zero to the lidar_port
```bash
roslaunch ouster_ros sensor.launch \ …
```

SW-4279: revise ouster-ros set_config/init_client sequence after release

---

src/os_client_base_nodelet.cpp
src/os_sensor_nodelet.cpp

Hi!
The code has some WARN level prints that really aren't warnings. I've changed these to INFO level prints.
I'm guessing they were made WARN so that they are easier to find in a long list of output, but I still think they're better off as INFO level statements. Having warnings in the log makes me think something is wrong and needs to be fixed. My brain automatically parses orange text as something bad, so I reckon it's best to avoid orange warnings when everything is good.
If you agree, feel free to merge.

Change informational prints from WARN to INFO

---

CHANGELOG.rst
include/ouster_ros/os_point.h
include/ouster_ros/os_ros.h
package.xml
src/os_cloud_nodelet.cpp
src/os_ros.cpp

* Depends on https://github.com/ouster-lidar/ouster_example/pull/470
* Closes #12 
* Closes #14
* Improve ROS driver performance
* Reduce CPU utilization by 1.5x - 1.7x
* Significantly reduce time delay to publish point clouds
* Improve driver stability
* Other changes
- BREAKING CHANGE: update ring type from `uint8_t` to `uint16_t`
- Add **pcl_ros** to as dependency to `package.xml`
* TODO

SW-4360: ouster-ros driver performance and stability optimizations

---

CHANGELOG.rst
package.xml

- https://github.com/ouster-lidar/ouster_example/pull/476
- https://github.com/ouster-lidar/ouster_example/pull/477
* ouster_client changes
- Bump versions for official release
- Signal multiplier bugfix for FW 3.0
- Metadata parsing robustification
- preliminary RAW_HEADERS support
- Update Changelog unreleased to release date
N/A

Update ouster-sdk to the 20230114 release

---

ouster-ros/CMakeLists.txt
ouster-ros/include/ouster_ros/os_processing_node_base.h
ouster-ros/launch/rviz.launch.py
ouster-ros/src/os_processing_node_base.cpp
ouster-ros/src/os_sensor_node.cpp

Minor fixes of some issues that merged during testing of ros2-foxy branch.
- Fixed missing .cpp file extension in ouster-ros CMakeLists.txt
- Fixed arguments of `static_transform_publishers` in `rviz.launch.py`
- Definition of `wait_time_per_attempt` was moved to `ouster-ros/src/os_processing_node_base.cpp` since it was causing undefined symbol error while loading library os_image_component and os_cloud_component library
- Publishers `lidar_packet_pub` and `imu_packet_pub` were converted to LifecyclePublishers and activated in `on_activate` callback. Otherwise I was getting `Trying to publish message on the topic 'XXX', but the publisher is not activated`
- Tested on Ubuntu 20.04, ROS2 foxy and Ouster OS0-128-U with FW 2.3.1 launching `sensor.independent.launch.py` since …

Quick fixes in ROS2 - Foxy 

---

.github/workflows/docker-image.yml
CHANGELOG.rst
CMakeLists.txt
LICENSE
README.md
include/ouster_ros/os_client_base_nodelet.h
include/ouster_ros/os_point.h
include/ouster_ros/os_ros.h
package.xml
src/os_client_base_nodelet.cpp
src/os_cloud_nodelet.cpp
src/os_image_nodelet.cpp
src/os_replay_nodelet.cpp
src/os_ros.cpp
src/os_sensor_nodelet.cpp

- related: #51
- related https://github.com/ouster-lidar/ouster_example/issues/481
- bugfix: Address an issue causing the driver to warn about missing non-legacy fields even they exist in the original metadata file
- Multiple code improvements
- Bump up copyright dates
- Update project title in the readme for the upcoming ros2 driver support
- Add status badges to the main page
- Add quick links to the new ros2 drivers
- Advertise the new `sensor_mtp.launch` launch file
Follow the instructions as provided in the [project readme](https://github.com/ouster-lidar/ouster-ros/blob/4653172a18192131f9c87d61150d7bf1c69e4b1d/README.md) to setup, build and run the project and check for the following:
- Building passing
- Test out the [three launch …

Update README about ROS2 and the new multicast feature + carry over some of the code improvements from ROS2 branch

---

CHANGELOG.rst
src/os_cloud_nodelet.cpp

Closes #47 
Related #46 
* Implement a technique to estimate `frame_ts` and `scan_ts` when packets are missing at beginning of a LIDAR scan
* The technique utilizes linear interpolation to impute the value of the frame time
- The timestamp of the very first frame is extrapolated based on column time spacing
> **Note**
> The `TIME_FROM_ROS_TIME` case extrapolates frame time based on the reception time of the first packet/column to arrive of a given frame.
* Launch with a live sensor and observe that the timestamp of point cloud messages stays timestamps consistent regardless of the existence of the missing packets.

Implement a technique to estimate scan_ts when packets are missing at beginning of a lidar scan

---

CHANGELOG.rst
src/os_image_nodelet.cpp

Addresses #65
- added `frame_id` information to image topics
- launch an ouster sensor node
- in a separate terminal use the command `rostopic echo --noarr` on any of the image topics
- The topic header should have the proper frame_id set

SW-4641: set-frame-id-of-published-images

---

ouster-ros/CMakeLists.txt

- closes #79 
- Explicity set cxx compile standard if the env isn't

SW-4785: ros-2 driver fails to start on jetsons (arm)

---

CHANGELOG.rst
README.md
include/ouster_ros/os_client_base_nodelet.h
include/ouster_ros/os_ros.h
launch/common.launch
launch/record.launch
launch/replay.launch
launch/sensor.launch
launch/sensor_mtp.launch
package.xml
src/os_client_base_nodelet.cpp
src/os_cloud_nodelet.cpp
src/os_image_nodelet.cpp
src/os_replay_nodelet.cpp
src/os_ros.cpp
src/os_sensor_nodelet.cpp

Implements changes for #80 for ros1.
Add a std_msgs/String latched publisher to os_sensor_nodelet.cpp.
In get_metadata() for both os_cloud_nodelet.cpp and os_image_nodelet.cpp:
- Add a std_msgs/String callback and subscriber.
- Manually spin until a service client becomes available or a non-empty config message has arrived. 
1. Launched sensor.launch with a live sensor, confirmed that the metadata source is from topic. Confirmed that point-clouds and images are published. 
2. Launched sensor.launch with config topic remapped (making topic unavailable) , confirmed that the metadata source is not from topic (from service). Confirmed that point-clouds and images are published.

ROS1 - Adding latched topic transport config/metadata

---

CHANGELOG.rst
README.md
ouster-ros/CMakeLists.txt
ouster-ros/config/metadata-qos-override.yaml
ouster-ros/include/ouster_ros/os_processing_node_base.h
ouster-ros/include/ouster_ros/os_ros.h
ouster-ros/include/ouster_ros/os_sensor_node_base.h
ouster-ros/launch/record.composite.launch.xml
ouster-ros/launch/replay.composite.launch.xml
ouster-ros/package.xml
ouster-ros/src/os_cloud_node.cpp
ouster-ros/src/os_image_node.cpp
ouster-ros/src/os_processing_node_base.cpp
ouster-ros/src/os_replay_node.cpp
ouster-ros/src/os_sensor_node.cpp
ouster-ros/src/os_sensor_node_base.cpp

- related #81
* added a new `/ouster/metadata` topic that is consumed by os_cloud and os_image nodes and save it to the bag file on record
* make specifying metadata file optional during record and replay modes as of package version 8.1
all functionality maintained

SW-4837: replace the use of ros service to retrieve sensor metadata with latched topics

---

CHANGELOG.rst
README.md
ouster-ros/CMakeLists.txt
ouster-ros/config/metadata-qos-override.yaml
ouster-ros/include/ouster_ros/os_processing_node_base.h
ouster-ros/include/ouster_ros/os_ros.h
ouster-ros/include/ouster_ros/os_sensor_node_base.h
ouster-ros/launch/record.independent.launch.xml
ouster-ros/launch/replay.independent.launch.xml
ouster-ros/package.xml
ouster-ros/src/os_cloud_node.cpp
ouster-ros/src/os_image_node.cpp
ouster-ros/src/os_processing_node_base.cpp
ouster-ros/src/os_replay_node.cpp
ouster-ros/src/os_sensor_node.cpp
ouster-ros/src/os_sensor_node_base.cpp

- Related #102 
* added a new `/ouster/metadata` topic that is consumed by os_cloud and os_image nodes and save it to the bag file on record
* make specifying metadata file optional during record and replay modes as of package version 8.1
all functionality maintained

SW-4837: replace the use of ros service to retrieve sensor metadata with latched topics foxy

---

CHANGELOG.rst
ouster-ros/launch/replay.independent.launch.xml
ouster-ros/package.xml

- N/A
- Drop the `--clock` from the ros2 bag play command under foxy
```bash
ros2 launch ouster_ros replay.launch.xml bag_file:=<bag_file> metadata:=<metadata.json>
```

Remove the --clock option in bag play

---

ouster-ros/config/parameters.yaml
ouster-ros/launch/sensor.composite.launch.xml
ouster-ros/launch/sensor.independent.launch.xml
ouster-ros/src/os_cloud_node.cpp

- Related #65
- Closes #95
- This PR removes `tf_prefix` from `os_cloud` node and replaces it with `sensor_frame`, `lidar_frame` and `imu_frame` parameters.
- These parameters are initialized with the same default value as sensor_frame, lidar_frame and imu_frame variable were before, and at the same time they are read (not need for the double get_parameter/declare_parameter call). Hence allowing them to be optionally set by the user.
...

Replace tf_prefix by sensor_frame, lidar_frame and imu_frame parameters

---

CHANGELOG.rst
ouster-ros/config/parameters.yaml
ouster-ros/launch/record.composite.launch.xml
ouster-ros/launch/replay.composite.launch.xml
ouster-ros/launch/rviz.launch.py
ouster-ros/launch/rviz.launch.xml
ouster-ros/launch/sensor.composite.launch.xml
ouster-ros/launch/sensor.independent.launch.xml
ouster-ros/launch/sensor_mtp.launch.xml
ouster-ros/package.xml
ouster-ros/src/os_cloud_node.cpp

- Parent PR #96
- Replace `tf_prefix` from **os_cloud** with `sensor_frame`, `lidar_frame` and `imu_frame` parameters.
* Defaults work 
```bash
ros2 launch ouster_ros sensor.launch.xml sensor_hostname:=$SENSOR_HOSTNAME
```
* Supplying a different frame names should reflected in the TF tree.
```bash
ros2 launch ouster_ros sensor.launch.xml sensor_hostname:=$SENSOR_HOSTNAME lidar_frame:=NEW_LIDAR_FRAME
```

SW-4924: Replace tf_prefix by sensor_frame lidar_frame and imu_frame parameters

---

CHANGELOG.rst
ouster-ros/config/parameters.yaml
ouster-ros/launch/replay.independent.launch.xml
ouster-ros/launch/rviz.launch.py
ouster-ros/launch/rviz.launch.xml
ouster-ros/launch/sensor.composite.launch.xml
ouster-ros/launch/sensor.independent.launch.xml
ouster-ros/launch/sensor_mtp.launch.xml
ouster-ros/package.xml
ouster-ros/src/os_cloud_node.cpp

- Parent PR #96
- Rolling/Humble Equivalent PR #115 
- Replace `tf_prefix` from **os_cloud** with `sensor_frame`, `lidar_frame` and `imu_frame` parameters.
* Defaults work 
```bash
ros2 launch ouster_ros sensor.launch.xml sensor_hostname:=$SENSOR_HOSTNAME
```
* Supplying a different frame names should reflected in the TF tree.
```bash
ros2 launch ouster_ros sensor.launch.xml sensor_hostname:=$SENSOR_HOSTNAME lidar_frame:=NEW_LIDAR_FRAME
```

SW-4924: replace tf_prefix by sensor_frame lidar_frame and imu_frame parameters (foxy)

---

ouster-ros/package.xml

- Related #113 
- Related #117 
- Drop `service_msgs` from ROS dependencies
- Build succeeds

Drop service_msgs from package.xml in ros2 foxy

---

ouster-ros/package.xml

- Closes #113 
- Related #118 
- Drop `service_msgs` from ROS dependencies
- Build succeeds

Drop service_msgs from ROS dependencies 

---

CHANGELOG.rst
ouster-ros/package.xml
ouster-ros/src/os_cloud_node.cpp
ouster-ros/src/os_sensor_node.cpp

- Closes #104
- Remove the use of static vars within sensor and cloud components
- Run two components of same type under the same process

SW-4859: enable having multiple components of same type under same process

---

CHANGELOG.rst
ouster-ros/package.xml
ouster-ros/src/os_cloud_node.cpp
ouster-ros/src/os_sensor_node.cpp

- Closes #104
- Remove the use of static vars within sensor and cloud components
- Test running two components of the same plugin type within the same container

SW-4859: enable having multiple components of same-type under same process

---

CHANGELOG.rst
ouster-ros/launch/record.composite.launch.xml
ouster-ros/launch/replay.composite.launch.xml
ouster-ros/launch/rviz.launch.py
ouster-ros/launch/rviz.launch.xml
ouster-ros/launch/sensor.composite.launch.py
ouster-ros/launch/sensor.composite.launch.xml
ouster-ros/launch/sensor.independent.launch.py
ouster-ros/launch/sensor.independent.launch.xml
ouster-ros/launch/sensor_mtp.launch.xml
ouster-ros/package.xml
ouster-ros/src/os_cloud_node.cpp

- parent #112
- ros2 foxy #125
- resolves #105 for ros2
- Send static transforms only once with a static transform broadcaster
- [optional] Launch sensor node (xml | py) and replay / record nodes.

SW-4972: merge switching to static transform publisher contribution

---

CHANGELOG.rst
ouster-ros/launch/record.independent.launch.xml
ouster-ros/launch/replay.independent.launch.xml
ouster-ros/launch/rviz.launch.py
ouster-ros/launch/rviz.launch.xml
ouster-ros/launch/sensor.composite.launch.py
ouster-ros/launch/sensor.composite.launch.xml
ouster-ros/launch/sensor.independent.launch.py
ouster-ros/launch/sensor.independent.launch.xml
ouster-ros/launch/sensor_mtp.launch.xml
ouster-ros/package.xml
ouster-ros/src/os_cloud_node.cpp

- parent #112
- ros2 rolling/humble #124
- resolves #105 for ros2
- Send static transforms only once with a static transform broadcaster
- [optional] Launch sensor node (xml | py) and replay / record nodes.

SW-4972: merge switching to static transform publisher contribution foxy

---

CHANGELOG.rst
package.xml
src/os_cloud_nodelet.cpp

- closes #105 
- related #9 
- Reduce the publish rate of tf transforms by publishing IMU TF transforms at the same rate as LIDAR TF transforms
> **Note:**
> Using **StaticTransformPublisher** is the proper thing to do but due to an issue that exists(or existed) in ROS1 which causes it to generate tons of warnings that couldn't be silenced as noted in #9 and also based on my own experience; so as a compromise I kept everything pretty much as is but reduced the publish rate of IMU TF transforms by publishing them at the same time as LIDAR TF transforms.  
- Before this change the total publish rate of TF messages generated by ROS driver would be at 120+ Hz.
- Launch a sensor with the ouster driver in one terminal and run a tf monitor in another terminal and observe the frequency of …

SW-4993: Reduce the publish rate of imu tf transforms

---

ouster-ros/config/parameters.yaml
ouster-ros/src/os_cloud_node.cpp
ouster-ros/src/os_sensor_node.cpp

- humble #140
- related #110 
- closes #120
- Deprecate the use of timers to poll data
- Existing functionality not affected

SW-4997: Switch from using ROS timer to threads for polling lidar data

---

ouster-ros/config/parameters.yaml
ouster-ros/src/os_cloud_node.cpp
ouster-ros/src/os_sensor_node.cpp

- foxy: #139 
- related #110
- closes #120 
- Switch from using ROS timers to thread for polling
- Specify defaults for non-required params
- Existing functionality maintained

SW-4997: Switch from using ROS timers to thread for polling lidar data

---

CHANGELOG.rst
ouster-ros/package.xml
ouster-ros/src/os_sensor_node.cpp
ouster-ros/src/point_cloud_processor.h

- fixes #146 
- Address an issue where the 2nd point cloud replaces the 1st one when using dual returns
Connect to a sensor with dual return enabled and observe both point clouds published accordingly

ROS compatibility mode dual returns fix

---

ouster-ros/config/driver_params.yaml
ouster-ros/launch/record.independent.launch.xml
ouster-ros/launch/replay.independent.launch.xml
ouster-ros/launch/rviz.launch.xml
ouster-ros/launch/sensor.composite.launch.xml
ouster-ros/launch/sensor.independent.launch.xml
ouster-ros/launch/sensor.launch.xml
ouster-ros/launch/sensor_mtp.launch.xml
ouster-ros/src/os_static_transforms_broadcaster.h

- related #149
- Use `SystemDefaultQoS` by default when recording/replaying
- Switch to using composite/merged driver node by default for `sensor.launch.xml` launch file.
- Initialize `point_cloud_frame` with an empty string
- Misc:
- Add missing param definitions to `record.independent.launch.xml` 
- Remove unused param definitions in `rviz.launch.xml` 
- Launch a live sensor using the xml launch file format setting only the value of the `sensor_hostname`
```bash
ros2 launch ouster_ros sensor.launch.xml \
sensor_hostname:=<sensor host>
```
Once the sensor connects verify that all topics are using a BEST_EFFORT policy using:
```bash
ros2 topic echo -v "topic_name"
```
- Launch `record.launch.xml` as follows:
```bash
ros2 launch ouster_ros record.launch.xml \
sensor_hostname:=<sensor host> …
```

SW-5167: fix black columns when recording a bag file

---

ouster-ros/config/driver_params.yaml
ouster-ros/launch/record.composite.launch.xml
ouster-ros/launch/replay.composite.launch.xml
ouster-ros/launch/rviz.launch.xml
ouster-ros/launch/sensor.composite.launch.xml
ouster-ros/launch/sensor.independent.launch.xml
ouster-ros/launch/sensor_mtp.launch.xml
ouster-ros/src/os_static_transforms_broadcaster.h

- related #162 
- related #146 
- Initialize `point_cloud_frame` with an empty string
- Expose cloud_frame through launch xml files
- Remove unused/duplicate param definitions
- Update launch files args descriptions
Launch a live sensor using the xml launch file format setting only the value of the sensor_hostname
ros2 launch ouster_ros sensor.launch.xml \
sensor_hostname:=<sensor host>
Once the sensor connects verify that all topics are using a BEST_EFFORT policy using:
ros2 topic echo -v "topic_name"
Launch record.launch.xml as follows:
ros2 launch ouster_ros record.launch.xml \
sensor_hostname:=<sensor host>          \
bag_file:=<bag file>
Once the sensor connects verify that all topics are using a RELIABLE policy using:
ros2 topic echo -v "topic_name"

SW-5167: follow ups from SW-5167-fix-black-columns-when-recording-under-ros-foxy

---

CHANGELOG.rst
include/ouster_ros/os_ros.h
package.xml
src/imu_packet_handler.h
src/lidar_packet_handler.h
src/os_image_nodelet.cpp
src/os_ros.cpp
src/point_cloud_processor.h

- ported from #187
- related #60 
- closes #61 
- related #66 
- Publish de-stagggered point cloud
- wrap all classes within the **ouster_ros** namespace
- Review test procedures

SW-5396: publish point cloud in destaggered form

---

CHANGELOG.rst
ouster-ros/config/viz-reliable.rviz
ouster-ros/include/ouster_ros/os_ros.h
ouster-ros/launch/record.independent.launch.xml
ouster-ros/launch/replay.independent.launch.xml
ouster-ros/package.xml
ouster-ros/src/imu_packet_handler.h
ouster-ros/src/laser_scan_processor.h
ouster-ros/src/lidar_packet_handler.h
ouster-ros/src/os_image_node.cpp
ouster-ros/src/os_ros.cpp
ouster-ros/src/point_cloud_processor.h
ouster-ros/src/thread_safe_ring_buffer.h

- ported from #182
- related #60 
- closes #61 
- related #66 
- Publish de-stagggered point cloud
- wrap all classes within the **ouster_ros** namespace
- add a `viz-reliable.rviz` configuration and use by default for record/replay senarios.
- Review test procedures

SW-5396: publish point cloud in destaggered form (foxy)

---

src/os_transforms_broadcaster.h

Add the tf_prefix also to the point cloud frame. Without these changes the frame_id of the published point cloud are without the namespace prefix. Therefore, do not match with the published tf_tree where the frames do have the namespace prefix.  
Set tf_prefix: e.g. tf_prefix="test"
check frame_id of the point cloud. 
check frames of the published tf_tree (e.g using rqt)

Add tf_prefix to point_cloud_frame

---

launch/common.launch
launch/record.launch
launch/sensor.launch
src/os_cloud_nodelet.cpp

Add `ptp_utc_tai_offset_secs` parameter to account for UTC/TAI offset.
International Atomic Time (TAI) is currently ahead of UTC by 37 seconds, so that is the default setting for the new parameter.
- Tested with OS0 32 beam lidar on robot with hardware ptp support with ptp4l and phc2sys running as services.
- Used the following command to launch the driver:
```
roslaunch ouster_ros sensor.launch sensor_hostname:=<sensor-ip> viz:=false timestamp_mode:=TIME_FROM_PTP_1588 lidar_mode:=1024x10 ptp_utc_tai_offset_secs:=-37
```
- Previously, timestamps for the point clouds published on `ouster/points` were in the future by approximately -36.9 seconds compared to UTC system time. After the change, the timestamps are now milliseconds in the past as expected. Similarly for the imu messages …

ROS-53: Add parameter for utc/tai offset in ptp mode.

---

src/os_ros.cpp

As far as I understand the staggered vs destaggered the time stamp of one column within a staggered image / point cloud is always the same. But in an destaggered image / point cloud represents the same azimuth value in one column. 
See [here](https://static.ouster.dev/sdk-docs/reference/lidar-scan.html#staggering-and-destaggering)
Therefore i would expect the timestamp of each point in the destaggered point cloud to be corected by the pixel shift as well.
#188 
#60
I applied the pixel shift to the timestamp as well
I tested it with an OS2, FW 2.5.2 with an follow up node for point cloud undistortion and it seem to work.

Destagger timestamp of each point as well

---

CHANGELOG.rst
Dockerfile
README.md
include/ouster_ros/os_ros.h
launch/common.launch
launch/driver.launch
launch/record.launch
launch/replay.launch
launch/sensor.launch
launch/sensor_mtp.launch
package.xml
src/imu_packet_handler.h
src/lidar_packet_handler.h
src/os_cloud_nodelet.cpp
src/os_driver_nodelet.cpp
src/os_ros.cpp
src/os_sensor_nodelet_base.cpp
src/os_transforms_broadcaster.h
src/point_cloud_processor.h

- Incorporated #53
- addresses #186
- ROS2 Humble: #195 
- ROS2 Foxy: #198 
* Add parameter for UTC/TAI offset in ptp mode.
* Don't alter the frame id for **LaserScan** messages.
Use a sensor with PTP mode and a host machine with sync enabled.
The sensor timestamps and the host machine timestamp should match (on the order of 10 microseconds)

SW-5459: add a parameter for utc/tai time offset

---

CHANGELOG.rst
ouster-ros/launch/driver.launch.py
ouster-ros/launch/sensor.composite.launch.py
ouster-ros/launch/sensor.independent.launch.py
ouster-ros/package.xml

- closes #209
- foxy/galactic PR: #214 
- Shutdown node if failed to connect to the sensor on startup rather than hanging.
- ~While sensor is properly wired launch **ouster_ros** through `driver.launch.py` or `sensor.independent.launch.py`~
- ~Verify the node configures and connects to the sensor as normal~
- ~Disconnect the sensor  and then launch **ouster_ros** through `driver.launch.py` or `sensor.independent.launch.py`~
- ~Verify the node fails to connect and then shuts down as expected with an error message.~
- Validated by issue reporter.

Shutdown when can not connect to sensor on startup in ROS2 (Humble/Iron)

---

CHANGELOG.rst
ouster-ros/launch/driver.launch.py
ouster-ros/launch/sensor.composite.launch.py
ouster-ros/launch/sensor.independent.launch.py
ouster-ros/package.xml

- closes #209
- humble/iron PR: #211
- Shutdown node if failed to connect to the sensor on startup rather than hanging.
- ~While sensor is properly wired launch **ouster_ros** through `driver.launch.py` or `sensor.independent.launch.py`~
- ~Verify the node configures and connects to the sensor as normal~
- ~Disconnect the sensor  and then launch **ouster_ros** through `driver.launch.py` or `sensor.independent.launch.py`~
- ~Verify the node fails to connect and then shuts down as expected with an error message.~
- Validated by issue reporter.

Shutdown when can not connect to sensor on startup in ROS2 (foxy/galactic)

---

ouster-ros/src/os_sensor_node.cpp

- resolves: #212
- Restore previous call of on_activate on imu/lidar packet topics
sensor.launch.xml

HOTFIX: call on_activate on imu/lidar packet topics

---

CHANGELOG.rst
launch/driver.launch
launch/record.launch
launch/replay.launch
launch/sensor.launch
launch/sensor_mtp.launch
package.xml
src/os_driver_nodelet.cpp
src/os_sensor_nodelet.cpp
src/os_sensor_nodelet.h

- N/A
- Stop publishers and any threads on nodelets destroy
- connect to a sensor, verify no crash reported on shutdown (either via `ctrl+c` or `rosnode kill`)

SW-5617: resolve issue with crash on exist in ros-1 driver

---

CHANGELOG.rst
ouster-ros/launch/record.composite.launch.xml
ouster-ros/launch/replay.composite.launch.xml
ouster-ros/launch/sensor.composite.launch.xml
ouster-ros/launch/sensor.independent.launch.xml
ouster-ros/launch/sensor_mtp.launch.xml
ouster-ros/package.xml
ouster-sensor-msgs/package.xml

- Follow ups to #216
- resolves #231 (adds a note to CHANGLOG.rst indicating that the default ptp_utc_tai_offset forms a breaking change).
- Add support to control `point_type` through `*.launch.xml` files
- Added a note to CHANGLOG.rst indicating that the default ptp_utc_tai_offset forms a breaking change.
Same steps to validate in #216 but utilize `*.launch.xml` format to set the `point_type` parameter.

SW-5466: Support Velodyne point type in the ROS driver amendments

---

CHANGELOG.rst
README.md
ouster-ros/CMakeLists.txt
ouster-ros/config/driver_params.yaml
ouster-ros/config/os_sensor_cloud_image_params.yaml
ouster-ros/include/ouster_ros/common_point_types.h
ouster-ros/include/ouster_ros/os_point.h
ouster-ros/include/ouster_ros/os_ros.h
ouster-ros/include/ouster_ros/sensor_point_types.h
ouster-ros/launch/sensor.composite.launch.xml
ouster-ros/launch/sensor.independent.launch.xml
ouster-ros/launch/sensor_mtp.launch.xml
ouster-ros/package.xml
ouster-ros/src/lidar_packet_handler.h
ouster-ros/src/os_cloud_node.cpp
ouster-ros/src/os_driver_node.cpp
ouster-ros/src/os_image_node.cpp
ouster-ros/src/os_ros.cpp
ouster-ros/src/os_sensor_node.cpp
ouster-ros/src/point_cloud_compose.h
ouster-ros/src/point_cloud_processor.h
ouster-ros/src/point_cloud_processor_factory.h
ouster-ros/src/point_meta_helpers.h
ouster-ros/src/point_transform.h
ouster-ros/src/thread_safe_ring_buffer.h
ouster-ros/test/point_accessor_test.cpp
ouster-ros/test/point_cloud_compose_test.cpp
ouster-ros/test/point_transform_test.cpp
ouster-sensor-msgs/package.xml

- ported from #216 
- resolves #15 
- resolves #29
- resolves #210 
- related #97
- related #217
- related #223
- added the ability to customize the published point clouds(s) to velodyne point cloud format and
other common pcl point types.
- made ouster_image_component operate separately from ouster_cloud_component
- Run the driver with default parameters and verify no observable behavioral changes.
- Change `point_type` parameter to `native` and verify that it reflects the same point cloud format that we get from the sensor.
- Change `point_type` parameter to `xyz` and verify that the published point cloud format only has `xyz` fields, regardless of the underlying sensor format.
- Change `point_type` parameter to `xyzi` and verify that the published point cloud format only has `xyz` …

SW-5466: Support velodyne point type in the ros driver (foxy)

---

CHANGELOG.rst
ouster-ros/package.xml
ouster-ros/src/os_driver_node.cpp
ouster-ros/src/os_sensor_node.cpp
ouster-ros/src/os_sensor_node.h
ouster-sensor-msgs/package.xml

- related #240
- resolves #247 
- Bump up ouster_client to 20231031 release
Ensure all functionality sustained with no drawbacks per testing procedures for ouster-ros

SW-5623: Bump up ouster_client to 20231031 release

---

CHANGELOG.rst
ouster-ros/package.xml
ouster-ros/src/os_driver_node.cpp
ouster-ros/src/os_sensor_node.cpp
ouster-ros/src/os_sensor_node.h
ouster-sensor-msgs/package.xml

- rolling/humble/iron equivalent #262
- related #240
- resolves #247 
- Bump up ouster_client to 20231031 release
Ensure all functionality sustained with no drawbacks per testing procedures for ouster-ros

Bump up ouster_client to 20231031 release

---

CHANGELOG.rst
CMakeLists.txt
package.xml

This fixes issues of including headers from ouster_client or nonstd when using install space.
Folder layout  on current master:
Note e.g. `os_point.h` being located in `install/include/ouster_ros/include/ouster_ros/os_point.h`
instead of just `install/include/ouster_ros/os_point.h` where I would expect it to be.
How `install/include` looks after this PR:
and so on..
This means that if you are using e.g. `stagger` function from `lidar_scan.h` in you own ros_pkg, you can now:
```
#include <ouster/lidar_scan.h>
ouster::stagger(my_img,pixel_shift_vec)
```
-
Update install path in CmakeLists.txt
Included header from ouster_client and compiled with install space. It works!

Cmakelists: Fix install directories

---

CHANGELOG.rst
README.md
ouster-ros/config/viz.rviz
ouster-ros/include/ouster_ros/os_ros.h
ouster-ros/package.xml
ouster-ros/src/laser_scan_processor.h
ouster-ros/src/os_cloud_node.cpp
ouster-ros/src/os_driver_node.cpp
ouster-ros/src/os_ros.cpp
ouster-ros/src/os_sensor_node.cpp

- ROS1: #224 
- ROS2 foxy: #204 
- resolves #196
- resolves #237 
- resolves #241
- Apply destagger to LaserScan message
- Add LaserScan object to RVIZ
- Fix an issue where LaserScan does not work properly with using dual mode
- Address an issue where LaserScan appeared different on FW prior to 2.4
- Make sure that the PointCloud and LaserScan fully aligned

ROS-196: laser scan from ros driver is not properly aligned with point cloud [humble]

---

CHANGELOG.rst
ouster-ros/package.xml
ouster-ros/src/os_sensor_node.cpp
ouster-sensor-msgs/package.xml

- foxy PR: #292
- closes: #288
- Use timeout when waiting for packets to be proceed in case no packets are coming
- driver functionality sustained
- launch a ros2 node then perform a set_config call with STANDBY mode, see the driver idles
- perform a follow set_config call this time with NORMAL mode and verify that driver resumes

ROS-288: ROS2 crashes when standby mode is set and then set to normal [HUMBLE]

---

ouster-ros/include/ouster_ros/os_point.h
ouster-ros/src/os_sensor_node.cpp
ouster-ros/src/point_cloud_compose.h
ouster-ros/src/point_cloud_processor_factory.h

None
Just some spelling fixes, mostly on comments except. Only function name that was changed was `make_point_cloud_procssor`.
--

docs: fix spelling mistakes

---

CHANGELOG.rst
CMakeLists.txt
package.xml
src/lidar_packet_handler.h
src/lock_free_ring_buffer.h
tests/lock_free_ring_buffer_test.cpp
tests/ring_buffer_test.cpp
tests/test_main.cpp

- Closes #240
- Closes #272
- Related #302
- ROS2[FOXY]: #320
- ROS2[HUMBLE/IRON]: #321
- When adding multiple subscribers or when having a bad network or low performing system, LidarScan composition and processing could eventually take more time, this leads to a build up in the packets buffer which will eventually be exhausted and the current mechanism of the thread_safe_ring_buffer::write_overwrite made things only worse. The solution can be in one of two things either ensure that the LidarScan composition + processing takes less time than the time needed to add new packets, or decouple packet addition from LidarScan consumption, if the consumption thread can't keep up then throttle. 
- Implement lock free ring buffer with unit tests
- Decouple packet reception from packet processing
- …

Implement lock free ring buffer with throttling [NOETIC]

---

CHANGELOG.rst
ouster-ros/CMakeLists.txt
ouster-ros/package.xml
ouster-ros/src/lidar_packet_handler.h
ouster-ros/src/lock_free_ring_buffer.h
ouster-ros/test/lock_free_ring_buffer_test.cpp
ouster-ros/test/ring_buffer_test.cpp
ouster-ros/test/test_main.cpp

- Closes #240
- Closes #272
- Related #302
- ROS1[NOETIC] #319 
- ROS2[FOXY] #320 
- When adding multiple subscribers or when having a bad network or low performing system, LidarScan composition and processing could eventually take more time, this leads to a build up in the packets buffer which will eventually be exhausted and the current mechanism of the thread_safe_ring_buffer::write_overwrite made things only worse. The solution can be in one of two things either ensure that the LidarScan composition + processing takes less time than the time needed to add new packets, or decouple packet addition from LidarScan consumption, if the consumption thread can't keep up then throttle. 
- Implement lock free ring buffer with unit tests
- Decouple packet reception from packet processing
- …

Implement lock free ring buffer with throttling [HUMBLE/IRON]

---

CHANGELOG.rst
ouster-ros/CMakeLists.txt
ouster-ros/config/community_driver.rviz
ouster-ros/config/viz-reliable.rviz
ouster-ros/package.xml
ouster-ros/src/lidar_packet_handler.h
ouster-ros/src/lock_free_ring_buffer.h
ouster-ros/test/lock_free_ring_buffer_test.cpp
ouster-ros/test/ring_buffer_test.cpp
ouster-ros/test/test_main.cpp

- Closes #240
- Closes #272
- Related #302
- ROS1[NOETIC] #319 
- ROS2[HUMBLE/IRON] #321 
- When adding multiple subscribers or when having a bad network or low performing system, LidarScan composition and processing could eventually take more time, this leads to a build up in the packets buffer which will eventually be exhausted and the current mechanism of the thread_safe_ring_buffer::write_overwrite made things only worse. The solution can be in one of two things either ensure that the LidarScan composition + processing takes less time than the time needed to add new packets, or decouple packet addition from LidarScan consumption, if the consumption thread can't keep up then throttle. 
- Implement lock free ring buffer with unit tests
- Decouple packet reception from packet processing …

Implement lock free ring buffer with throttling [FOXY]

---

CHANGELOG.rst
include/ouster_ros/sensor_point_types.h
launch/driver.launch
launch/record.launch
launch/sensor.launch
launch/sensor_mtp.launch
package.xml
src/impl/cartesian.h
src/os_cloud_nodelet.cpp
src/os_driver_nodelet.cpp
src/os_ros.cpp
src/point_cloud_processor.h
src/point_cloud_processor_factory.h

- #335
- Add support for the FUSA profile
- Set xyz values of individual points in the PointCloud to NaNs when range is zero
- Using a rev7 sensor with FW 3.1+, run the following command:
```bash
roslaunch ouster_ros sensor.launch \
sensor_hostname:=$SENSOR_IP \
udp_profile_lidar:=FUSA_RNG15_RFL8_NIR8_DUAL
```

Support FUSA dual returns udp profile [NOETIC]

---

CHANGELOG.rst
ouster-ros/config/driver_params.yaml
ouster-ros/include/ouster_ros/sensor_point_types.h
ouster-ros/launch/record.composite.launch.xml
ouster-ros/launch/sensor.composite.launch.xml
ouster-ros/launch/sensor.independent.launch.xml
ouster-ros/launch/sensor_mtp.launch.xml
ouster-ros/package.xml
ouster-ros/src/impl/cartesian.h
ouster-ros/src/os_cloud_node.cpp
ouster-ros/src/os_driver_node.cpp
ouster-ros/src/os_ros.cpp
ouster-ros/src/point_cloud_processor.h
ouster-ros/src/point_cloud_processor_factory.h

- #334 
- #336 
- Add support for the FUSA profile
- Set xyz values of individual points in the PointCloud to NaNs when range is zero
Using a rev7 sensor with FW 3.1+, run the following command:
`roslaunch ouster_ros sensor.launch params_file:=$PARAMS_FILE`
while having `udp_profile_lidar: FUSA_RNG15_RFL8_NIR8_DUAL` in the yaml file

Support FUSA dual returns udp profile [HUMBLE/IRON]

---

CHANGELOG.rst
ouster-ros/config/driver_params.yaml
ouster-ros/include/ouster_ros/sensor_point_types.h
ouster-ros/launch/record.independent.launch.xml
ouster-ros/launch/sensor.composite.launch.xml
ouster-ros/launch/sensor.independent.launch.xml
ouster-ros/launch/sensor_mtp.launch.xml
ouster-ros/package.xml
ouster-ros/src/impl/cartesian.h
ouster-ros/src/os_cloud_node.cpp
ouster-ros/src/os_driver_node.cpp
ouster-ros/src/os_ros.cpp
ouster-ros/src/point_cloud_processor.h
ouster-ros/src/point_cloud_processor_factory.h

- #334 
- #335 
- Add support for the FUSA profile
- Set xyz values of individual points in the PointCloud to NaNs when range is zero
Using a rev7 sensor with FW 3.1+, run the following command:
`roslaunch ouster_ros sensor.launch params_file:=$PARAMS_FILE`
while having `udp_profile_lidar: FUSA_RNG15_RFL8_NIR8_DUAL` in the yaml file

Support FUSA dual returns udp profile [GALACTIC/FOXY]

---

CHANGELOG.rst
CMakeLists.txt
README.md
launch/replay.launch
launch/replay_pcap.launch
ouster_ros_nodelets.xml
package.xml
src/os_pcap_nodelet.cpp

- related #353 
- related #355 
- closes #7 
- closes #13
- related #48
- #172
- closes #192
- related #333
- Implement a pcap reader nodelet
- Pace scans by the packets timestamps
- Conditionality enable and link the pcap library
- Display progress
* Enable `PCAP_BUILD` flag and build the driver then execute:
```bash
roslaunch ouster_ros replay_pcap.launch \
pcap_file:=... \
metadata:= ..
```

ROS[NOETIC] Add a pcap source reader nodelet

---

CHANGELOG.rst
README.md
ouster-ros/CMakeLists.txt
ouster-ros/launch/replay.independent.launch.xml
ouster-ros/launch/replay_pcap.launch.xml
ouster-ros/package.xml
ouster-ros/src/os_pcap_node.cpp

- related #344
- related #355
- closes #7 
- closes #13
- related #48
- #172
- closes #192
- related #333
- Implement a pcap reader node
- Pace scans by the packets timestamps
- Conditionality enable and link the pcap library
- Display progress
* Enable `PCAP_BUILD` flag and build the driver then execute:
```bash
ros2 launch ouster_ros replay_pcap.launch.xml \
pcap_file:=... \
metadata:= ..
```

ROS2[FOXY] add pcap reader

---

CHANGELOG.rst
README.md
ouster-ros/CMakeLists.txt
ouster-ros/launch/replay_pcap.launch.xml
ouster-ros/package.xml
ouster-ros/src/os_pcap_node.cpp

- related #344
- related #353 
- closes #7 
- closes #13
- related #48
- #172
- closes #192
- related #333
- Implement a pcap reader nodelet
- Pace scans by the packets timestamps
- Conditionality enable and link the pcap library
- Display progress
* Enable `PCAP_BUILD` flag and build the driver then execute:
```bash
ros2 ouster_ros replay_pcap.launch.xml \
pcap_file:=... \
metadata:= ..
```

ROS2[HUMBLE/IRON] add pcap reader

---

CHANGELOG.rst
launch/driver.launch
launch/record.launch
launch/replay.launch
launch/sensor.launch
launch/sensor_mtp.launch
package.xml
src/os_sensor_nodelet.cpp
src/os_sensor_nodelet.h

- closes #138
- related #227
* Set LIDAR FOV on startup
* Add an option to persist the config
* Run the node with azimuth start and stop as follows 
```bash
roslaunch ouster_ros driver.launch \
azimuth_window_start:=150000 \
azimuth_window_end:=250000
```
Verify that the azimuth window is cropped to selection 
* Run the node with `persist_config` set **true** as follows 
```bash
roslaunch ouster_ros driver.launch \
<pass a selection of settings> \
persist_config:=true
```
Verify that the new settings persist after power up/down cycle of the sensor

ROS-227: Set LIDAR FOV on startup and add an option to persist the config [NOETIC]

---

CHANGELOG.rst
ouster-ros/config/driver_params.yaml
ouster-ros/config/os_sensor_cloud_image_params.yaml
ouster-ros/launch/record.composite.launch.xml
ouster-ros/launch/replay.composite.launch.xml
ouster-ros/launch/sensor.composite.launch.xml
ouster-ros/launch/sensor.independent.launch.xml
ouster-ros/launch/sensor_mtp.launch.xml
ouster-ros/package.xml
ouster-ros/src/os_sensor_node.cpp
ouster-ros/src/os_sensor_node.h

- related #138
- closes #227
- relatd #356 
- related #358 
* Set LIDAR FOV on startup
* Add an option to persist the config
* Run the node with azimuth start and stop as follows 
```bash
ros2 ouster_ros sensor.launch \
azimuth_window_start:=150000 \
azimuth_window_end:=250000
```
Verify that the azimuth window is cropped to selection 
* Run the node with `persist_config` set **true** as follows 
```bash
ros2 ouster_ros sensor.launch.xml \
<pass a selection of settings> \
persist_config:=true
```
Verify that the new settings persist after power up/down cycle of the sensor
* Update the ros2 `driver_params.yaml` to set azimuth window start/end and the persist_config flag then launch the driver using:
```bash
ros2 launch ouster_ros driver.launch.py
```
Verify that the new settings persist …

ROS-227: Set LIDAR FOV on startup and add an option to persist the config [HUMBLE/IRON]

---

CHANGELOG.rst
ouster-ros/config/driver_params.yaml
ouster-ros/config/os_sensor_cloud_image_params.yaml
ouster-ros/launch/record.independent.launch.xml
ouster-ros/launch/replay.independent.launch.xml
ouster-ros/launch/sensor.composite.launch.xml
ouster-ros/launch/sensor.independent.launch.xml
ouster-ros/launch/sensor_mtp.launch.xml
ouster-ros/package.xml
ouster-ros/src/os_sensor_node.cpp
ouster-ros/src/os_sensor_node.h

- related #138
- closes #227
- relatd #356
- related #357 
* Set LIDAR FOV on startup
* Add an option to persist the config
* Run the node with azimuth start and stop as follows 
```bash
ros2 ouster_ros sensor.launch \
azimuth_window_start:=150000 \
azimuth_window_end:=250000
```
Verify that the azimuth window is cropped to selection 
* Run the node with `persist_config` set **true** as follows 
```bash
ros2 ouster_ros sensor.launch.xml \
<pass a selection of settings> \
persist_config:=true
```
Verify that the new settings persist after power up/down cycle of the sensor
* Update the ros2 `driver_params.yaml` to set azimuth window start/end and the persist_config flag then launch the driver using:
```bash
ros2 launch ouster_ros driver.launch.py
```
Verify that the new settings persist …

ROS-227: Set LIDAR FOV on startup and add an option to persist the config [FOXY]

---

CMakeLists.txt

When using current master with `BUILD_PCAP` set to default value `OFF` i got the following error:
This seems to stem from that pcap_node is linked into the nodelets library regardless of the `BUILD_PCAP` cmake arg
Tested on my robot with ouster lidar. `roslaunch ouster_ros sensor.launch <my_args>` now runs as expected

Link pcap nodelet only if BUILD_PCAP is defined

---

.github/workflows/docker-image.yml
CHANGELOG.rst
README.md
ouster-ros/config/driver_params.yaml
ouster-ros/config/os_sensor_cloud_image_params.yaml
ouster-ros/include/ouster_ros/os_sensor_node_base.h
ouster-ros/launch/record.composite.launch.xml
ouster-ros/launch/replay.composite.launch.xml
ouster-ros/launch/replay_pcap.launch.xml
ouster-ros/launch/sensor.composite.launch.py
ouster-ros/launch/sensor.composite.launch.xml
ouster-ros/launch/sensor.independent.launch.xml
ouster-ros/launch/sensor_mtp.launch.xml
ouster-ros/package.xml
ouster-ros/src/lidar_packet_handler.h
ouster-ros/src/os_pcap_node.cpp
ouster-ros/src/os_replay_node.cpp
ouster-ros/src/os_sensor_node.cpp
ouster-ros/src/os_sensor_node.h
ouster-ros/src/os_sensor_node_base.cpp

- related #55
- resolves #119
- resolves #233
- related #332
- resolves #337
- Implement sensor reconnection behavior
- Handle sensor reconfiguration from a cold start
- Add a flag to enable sensor reconnect (default disabled)
- properly handle config change outside of the ros driver
- only persist config startup config if persist_config was set
- only `auto_udp` if startup config didn't set an address
- added a parameter to set the dromant period between re-connection attempts
- added a parameter to set the maximum number of subsequent failed re-connection attempts
- added ROS Jazzy to the build :tada:
- added `auto_start` flag
- Doesn't handle invalid configurations gracefully
* Use the driver with default configuration to connect to a sensor & verify normal activity
* Enable the …

ROS-119: ouster-ros driver automatic reconnection [HUMBLE/IRON/JAZZY]

---

ouster-ros/launch/replay.independent.launch.xml

- resolves #368
- Fix replay unknown substitution arg
- `ros2 launch ouster_ros replay.launch.xml` works as described in `README.md`

ROS-368[GALACTIC|FOXY]: unable to use the replay mode due to unknown substitution arg

---

CHANGELOG.rst
ouster-ros/package.xml
ouster-ros/src/os_driver_node.cpp
ouster-ros/src/os_pcap_node.cpp
ouster-ros/src/os_sensor_node.cpp

- closes #382
- Fix `os_driver` _fails_when_raw_option_is_enabled
- Replace lifecycle_publisher with regular publisher for the os_pcap
- Adding a RAW token to the proc_mask doesn't brick the driver.
```bash
ros2 launch ouster_ros driver.launch.xml ... proc_mask:="PCL|RAW"
```

HOTFIX/ROS-382: os_driver fails when raw option is enabled

---

CHANGELOG.rst
ouster-ros/package.xml
ouster-ros/src/point_cloud_compose.h

- resolves #350
- Don't apply offset to destaggered timestamps within the point cloud
- Make sure the the timestamps align correctly when destaggerd is option is OFF
* run the driver with default option (destaggered=ON, organized=ON)
-  observe that the timestamps are consistent
* run the driver with default option (destaggered=OFF, organized=ON)
- observe that the timestamps appear staggerd

ROS-350[HUMBLE/IRON/JAZZY]: 't' timestamp field content is not plausible

---

.github/ISSUE_TEMPLATE/bug_report.md
README.md
util/network-configure.bash

- related #378
- Add a utility script for applying recommended network settings
- Mention it in the README
- N/A

Add a section for network config recommendation

---

ouster-ros/src/os_cloud_node.cpp
ouster-ros/src/os_driver_node.cpp
ouster-ros/src/os_static_transforms_broadcaster.h

This PR adds the parameter `pub_static_tf`, by default `True`, to control if the user wants or not to have the driver node publishing the static transform between the sensor frames.
It is useful to have it disabled in systems where a calibration process directly modifies the tf of the point cloud frame.

Add parameter to optionally disable the publication  of the static tf

---

CHANGELOG.rst
launch/common.launch
launch/driver.launch
launch/record.launch
launch/replay.launch
launch/replay_pcap.launch
launch/sensor.launch
launch/sensor_mtp.launch
package.xml
src/os_cloud_nodelet.cpp
src/os_driver_nodelet.cpp
src/os_pcap_nodelet.cpp
src/os_transforms_broadcaster.h

- https://github.com/ouster-lidar/ouster-ros/pull/393
* Remap `/metadata` topic
* Support **loop** capability in pcap replay
* Add `play_delay` to regular replay and pcap replay
* Expose `play_rate` for the bag file replay
* Added a launch file parameter `pub_static_tf` to disable sensor transforms broadcast 
* Test the newly exposed flags for `replay_pcap`
```bash
roslaunch ouster_ros replay_pcap.launch pcap_file:=<...> json_file:=<...> loop:=true play_delay:=10
```
* Test the newly exposed flags for bag `replay`
```bash
roslaucn ouster_ros replay_pcap.launch bag_file:=<...> loop:=true play_delay:=10 play_rate:=1.5
```
* Test that setting `pub_static_tf` to `false` disables the publish of sensor tf transforms:

ROS-389 [noetic]: replay-improvments-and-fixes

---

CHANGELOG.rst
ouster-ros/config/driver_params.yaml
ouster-ros/config/os_sensor_cloud_image_params.yaml
ouster-ros/include/ouster_ros/os_sensor_node_base.h
ouster-ros/launch/record.composite.launch.xml
ouster-ros/launch/replay.composite.launch.xml
ouster-ros/launch/replay_pcap.launch.xml
ouster-ros/launch/sensor.composite.launch.xml
ouster-ros/launch/sensor.independent.launch.xml
ouster-ros/launch/sensor_mtp.launch.xml
ouster-ros/package.xml
ouster-ros/src/os_cloud_node.cpp
ouster-ros/src/os_driver_node.cpp
ouster-ros/src/os_pcap_node.cpp
ouster-ros/src/os_sensor_node.cpp
ouster-ros/src/os_sensor_node.h
ouster-ros/src/os_sensor_node_base.cpp
ouster-ros/src/os_static_transforms_broadcaster.h

- related: #392
- resolves: #153
- resolves #389
- integrates: #330
* Remap `/metadata` topic
* Support **loop** capability in pcap replay
* Add `play_delay` to regular replay and pcap replay
* Expose `play_rate` for the bag file replay
* Added a parameter `pub_static_tf` to disable tf tansforms broadcast 
* Test the newly exposed flags for `replay_pcap`
```bash
ros2 launch ouster_ros replay_pcap.launch.xml pcap_file:=<...> json_file:=<...> loop:=true play_delay:=10
```
* Test the newly exposed flags for bag `replay`
```bash
ros2 launch ouster_ros replay_pcap.launch.xml bag_file:=<...> loop:=true play_delay:=10 play_rate:=1.5
```
* Test that setting `pub_static_tf` to `false` disables the publish of sensor tf transforms

ROS-389 [rolling/humble/iron/jazzy]: replay-improvments-and-fixes

---

launch/record.launch

- closes #398 
- Fix a typo in record.launch and other parameters 
- Call record.launch and verify it successfully captures the bag file from the sensor.
- Replay the generated bag file using replay.launch

ROS-398-fix-record-launch

---

launch/replay.launch

- closes #403
Set the default value of the bag file param in replay to an empty string so that the launch will not crash on this line: https://github.com/ouster-lidar/ouster-ros/blob/1dbdbb4317fa8f38ffb442513f889e379fe125ab/launch/replay.launch#L121
Run `roslaunch ouster_ros replay.launch` and see that it does not crash

Set the default value of the bag file param in replay to an empty string

---

src/os_sensor_nodelet.cpp

#410
Perform a check for a nullptr on unique pointer type before usage, that otherwise has the capacity to be null when not initialised due to the sensor not being powered on start-up.
Tested on-site

Check sensor connection thread validity before joining

---

CHANGELOG.rst
CMakeLists.txt
include/ouster_ros/os_ros.h
launch/driver.launch
launch/record.launch
launch/sensor.launch
launch/sensor_mtp.launch
msg/Telemetry.msg
package.xml
src/imu_packet_handler.h
src/lidar_packet_handler.h
src/os_cloud_nodelet.cpp
src/os_driver_nodelet.cpp
src/os_image_nodelet.cpp
src/os_ros.cpp
src/os_sensor_nodelet.cpp
src/os_sensor_nodelet.h
src/point_cloud_compose.h
src/telemetry_handler.h

* Related: #200
* Define a new telemetry message and emit (it from a live sensor or bag file or pcap) 
* Always set timestamps in the PointCloud even for invalid points
* Code refactor for LidarPacketHandler
* ~Support emitting Telemetry topic in replay mode (bag|pcap)~
- ~Probably in a separate PR~ 
* Launch a live sensor with telemetry enabled
```bash
roslaunch ouster_ros driver.launch sensor_hostname:=... proce_mask:="...|TLM"
```
* Once sensor is connected, open a separate terminal launch, verify that the telemetry topic is up and running
```bash
rostopic echo /ouster/telemetry
```
* Verify that the telemetry messages are being sent at the same rate as the raw packets topic
```bash
rostopic hz /ouster/telemetry
```

SW-6906: publish sensor telemetry in ouster ros

---

ouster-ros/launch/replay.composite.launch.xml
ouster-ros/src/os_replay_node.cpp

- Related #389
- Avoid the need to use execute commands by enabling `auto_start` similar to the `os_pcap` node. 
The launch file works with no issues
```
ros2 ouster_ros replay.launch bag_file:=<...>
```

ROS2 enable replay auto start

---

CHANGELOG.rst
launch/common.launch
launch/driver.launch
launch/record.launch
launch/replay.launch
launch/replay_pcap.launch
launch/sensor.launch
launch/sensor_mtp.launch
src/lidar_packet_handler.h
src/os_cloud_nodelet.cpp
src/os_driver_nodelet.cpp
src/os_image_nodelet.cpp

- Related #268
* Skip the lidar_scan based on a predefined percentage of the minimum number of valid columns in scan
* Launch a node as usual but enable the new `min_scan_valid_columns_ratio` parameter (set a high value)
```bash
roslaunch ouster_ros driver.launch sensor_hostname:=... min_scan_valid_columns_ratio:=0.9
```
* Observe the warning messages whenever the number of valid columns drops below the set amount:
```bash
[ WARN] [1738283732.021510354]: number of valid columns per scan 160 which is below the ratio 90%% SKIPPING SCAN
[ WARN] [1738283732.080962740]: number of valid columns per scan 304 which is below the ratio 90%% SKIPPING SCAN
```

ROS-268-min-valid-cols-lidar-scan

---

CHANGELOG.rst
ouster-ros/config/driver_params.yaml
ouster-ros/launch/record.composite.launch.xml
ouster-ros/launch/replay.composite.launch.xml
ouster-ros/launch/replay_pcap.launch.xml
ouster-ros/launch/sensor.composite.launch.xml
ouster-ros/launch/sensor.independent.launch.xml
ouster-ros/src/lidar_packet_handler.h
ouster-ros/src/os_cloud_node.cpp
ouster-ros/src/os_driver_node.cpp
ouster-ros/src/os_image_node.cpp

- Related #268
* Skip the lidar_scan based on a predefined percentage of the minimum number of valid columns in scan
* Edit `driver_params.yaml` to set the sensor name and set `min_scan_valid_columns_ratio` value to a high value `0.9`
* Launch a node as usual `ros2 ouster_ros driver.launch.py`
* Observe the warning messages whenever the number of valid columns drops below the set amount:
```bash
[ WARN] [1738283732.021510354]: number of valid columns per scan 160 which is below the ratio 90% SKIPPING SCAN
[ WARN] [1738283732.080962740]: number of valid columns per scan 304 which is below the ratio 90% SKIPPING SCAN
```

Port the changes to ROS2

---

CHANGELOG.rst
ouster-ros/CMakeLists.txt
ouster-ros/package.xml

This PR is similar in nature to https://github.com/ouster-lidar/ouster-ros/pull/258 except targeting the ros2 branch. I've found that before these changes, I am not able to include the header files in ouster_ros when using the install space.
Before, the file tree under `install/ouster_ros/include` looked like this:
After the changes the file tree under `install/ouster_ros/include` is the following which makes more sense.
Updates install path in Cmakelists.txt
Was able to include ouster_ros headers (like `#include <ouster_ros/os_ros.h>`) in my project and it can now compile!

[ros2] Fix ouster_ros install directories for easy include by dependent nodes

---

CHANGELOG.rst
ouster-ros/launch/record.composite.launch.xml

- Related #306 
* Add ``storage`` launch parameter to ``record.launch.xml``
```
ros2 launch ouster_ros record.launch.xml \
sensor_hostname:=<sensor-url> \
bag_file:=<destination> \
storage:=sqlite3
```
or
```
ros2 launch ouster_ros record.launch.xml \
sensor_hostname:=<sensor-url> \
bag_file:=<destination> \
storage:=mcap
```

Add a new storage param to record.launch.xml

---

CHANGELOG.rst
ouster-ros/config/driver_params.yaml
ouster-ros/include/ouster_ros/os_ros.h
ouster-ros/launch/replay.independent.launch.xml
ouster-ros/launch/replay_pcap.launch.xml
ouster-ros/launch/sensor.composite.launch.py
ouster-ros/launch/sensor.composite.launch.xml
ouster-ros/launch/sensor.independent.launch.xml
ouster-ros/launch/sensor_mtp.launch.xml
ouster-ros/package.xml
ouster-ros/src/impl/cartesian.h
ouster-ros/src/lidar_packet_handler.h
ouster-ros/src/os_cloud_node.cpp
ouster-ros/src/os_driver_node.cpp
ouster-ros/src/os_sensor_node.cpp
ouster-ros/src/os_sensor_node.h
ouster-ros/src/point_cloud_compose.h
ouster-ros/src/point_cloud_processor.h
ouster-ros/src/point_cloud_processor_factory.h

- Related: #362
- Related: #369
- Add `auto_start` flag to support start without using events or execute cmd
- Add a flag to control the publish of organized point cloud vs non-organized
- Add a flag to control the publish of destaggerd point cloud vs staggered
- Add parameter to set the min/max lidar range on generated point clouds
- Verify that all sensor launch files work as expected after the execute commands have been removed
- Verify that the newly added features:
- When `destagger` is set to false verify the driver doesn't destagger the published point cloud
- When `organized` is set to false verify that the published point cloud isn't 2D
- Adjust `min_range` and `max_range` and observe the point cloud shrink accordingly.

Cherry-pick node auto-start to ros2-foxy

---

CHANGELOG.rst
ouster-ros/package.xml
ouster-ros/src/os_cloud_node.cpp
ouster-ros/src/os_image_node.cpp

- closes #317 
- Use the node clock to ensure it follows the sim time in replay mode
- ROS messages follow the sim time

ROS-317: Fix simulation in replay mode

---

CHANGELOG.rst
launch/common.launch
launch/driver.launch
launch/record.launch
launch/replay.launch
launch/replay_pcap.launch
launch/sensor.launch
launch/sensor_mtp.launch
package.xml
src/os_cloud_nodelet.cpp
src/os_driver_nodelet.cpp

- Closes #175
- Include #191 
- ROS2: #444 
* Expose the vertical beam reduction value
```bash
roslaunch ... driver.launch sensor_hostname:=<source_url> v_reduction:=2
```
or
```bash
roslaunch ... replay.launch bag_file:=<source_url> v_reduction:=2
```
and observe the number of beams are reduced by the specified factor with respect to the original beam count of the sensor.

[ROS1] Expose the vertical beam reduction param

---

CHANGELOG.rst
CMakeLists.txt
include/ouster_ros/os_ros.h
launch/common.launch
launch/driver.launch
launch/record.launch
launch/replay.launch
launch/replay_pcap.launch
launch/sensor.launch
launch/sensor_mtp.launch
package.xml
src/image_processor.h
src/os_cloud_nodelet.cpp
src/os_driver_nodelet.cpp
src/os_image_nodelet.cpp
src/os_ros.cpp
src/point_cloud_processor.h
src/point_cloud_processor_factory.h

- None
- Implemented a mask filter on the received LidarScan.
- The mask is applied to the cloud + the image messages
- If the supplied mask size is different from the received LidarScan, the driver will resize the mask to match incoming scans size.
* Test out a sequence without applying a mask:
* Generate any mask composed of Black/White pixels, such as:
* Apply the mask as follows:
```bash
roslaunch ouster_ros driver.launch sensor_hostname:=<source_url> mask_path:=<path/to/mask.png>
```
* Observe the masked image in RVIZ/image_view:
* Observe the mask cloud in RVIZ/cloud_view

PointCloud mask

---

.github/workflows/docker-image.yml
CHANGELOG.rst
Dockerfile
README.md
ouster-ros/CMakeLists.txt
ouster-ros/config/driver_params.yaml
ouster-ros/include/ouster_ros/os_ros.h
ouster-ros/launch/record.composite.launch.xml
ouster-ros/launch/replay.composite.launch.xml
ouster-ros/launch/replay_pcap.launch.xml
ouster-ros/launch/sensor.composite.launch.xml
ouster-ros/package.xml
ouster-ros/src/image_processor.h
ouster-ros/src/os_cloud_node.cpp
ouster-ros/src/os_driver_node.cpp
ouster-ros/src/os_image_node.cpp
ouster-ros/src/os_ros.cpp
ouster-ros/src/point_cloud_processor.h
ouster-ros/src/point_cloud_processor_factory.h

- ROS1: #460
- Implemented a mask filter on the received LidarScan.
- The mask is applied to the cloud + the image messages
- If the supplied mask size is different from the received LidarScan, the driver will resize the mask to match incoming scans size.
* Test out a sequence without applying a mask:
* Generate any mask composed of Black/White pixels, such as:
* Apply the mask as follows:
```bash
roslaunch ouster_ros driver.launch sensor_hostname:=<source_url> mask_path:=<path/to/mask.png>
```
* Observe the masked image in RVIZ/image_view:
* Observe the mask cloud in RVIZ/cloud_view

Port the pointcloud mask feature to ROS2

---

src/point_cloud_compose.h

With the old logic, cloud.is_dense will only be set to true if every single point in the cloud has a NaN coordinate.
Replace
`cloud.is_dense &= xyz.isNaN().any();`
with
`cloud.is_dense &= !xyz.isNaN().any();`
now is_dense is true if no points in cloud are nan, false otherwise
Testing by altering the `invalid` arg in ouster::cartesianT
Before:
* `std::numeric_limits<float>::quiet_NaN()` -> `is_dense = False`
* `0.0f` -> `is_dense = False` 
After:
* `std::numeric_limits<float>::quiet_NaN()` -> `is_dense = False`
* `0.0f` -> `is_dense = True`

Fix .is_dense logic for pointcloud

---

CMakeLists.txt

This MR updates the CMake configuration to improve build compatibility for macOS
(Intel & Apple Silicon) when using ROS Noetic in an Anaconda environment.
- Added APPLE-specific linking logic to avoid unsupported `-Wl,--whole-archive` flags.
- Linked `${OUSTER_TARGET_LINKS}` directly for `ouster_ros`, nodelets, and tests on macOS.
- Maintained existing GNU ld behavior for non-Apple platforms.
- Verified successful build on macOS (Apple Silicon) with Anaconda-based ROS Noetic.
- Confirmed runtime with live OS1 sensor.

Build: Update CMakeLists.txt for macOS (Anaconda) compatibility

---

CHANGELOG.rst
CMakeLists.txt
package.xml

- Resolves #485
- Related #481 
- Drop whole archive linkage of ouster-client in ouster-ros
Builds on all supported platforms, execution maintained, double free error on shutdown is gone.

Drop whole archive linkage of ouster-client in ouster-ros

---

CHANGELOG.rst
ouster-ros/CMakeLists.txt
ouster-ros/package.xml

- Resolves #485 
- ROS1 #486 
* Drop whole archive linkage of ouster-client
Builds on all supported platforms, execution maintained, double free error on shutdown is gone

[ROS2] Drop whole archive linkage of ouster-client
